### ISSUE TITLE
Standalone converter

### ISSUE THREAD

**Issue by mantielero** [Terrev/3DXML-to-OBJ#7]
Are you planning to release a Linux version? Even better if this were a standalone tool.

If not, where I can find information about reading 3dxml files?

**Comment by Terrev** [comment]
Hello! This program is made for a pretty specific use case - captures of LEGO Digital Designer produced by 3DVia Printscreen. 3DVia Printscreen is only on Windows, so that's all I compiled it for.

If you want to do other stuff with the format, your best chance may be to take whatever's here as a base, and make a tool of your own - here's some format documentation that may help, too: https://www.3ds.com/3ds-passport/downloads/

**Comment by mantielero** [comment]
I wasn't aware of the format being documented. Thanks a lot.
